# Generated by Django 3.2.5 on 2022-02-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='clubs',
            new_name='memberships',
        ),
    ]
