# Generated by Django 3.2.5 on 2022-03-16 05:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0007_alter_club_meeting_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN must have atleast 10 capital alphabet or numberic characters.', regex='^([A-Z]|[0-9]){10,}$')])),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('year_of_publication', models.IntegerField()),
                ('publisher', models.CharField(max_length=100)),
                ('image_url_s', models.URLField()),
                ('image_url_m', models.URLField()),
                ('image_url_l', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('deadline', models.DateTimeField()),
                ('book_chooser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('chosen_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book_clubs.book')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_clubs.club')),
            ],
        ),
    ]
