# Generated by Django 3.2.5 on 2022-03-16 05:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0008_book_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Rating must not be lower than 0.'), django.core.validators.MaxValueValidator(limit_value=10, message='Rating must not be greater than 10.')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_clubs.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
