# Generated by Django 3.2.5 on 2022-03-16 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0009_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['isbn']},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['deadline']},
        ),
        migrations.AddField(
            model_name='user',
            name='rated',
            field=models.ManyToManyField(related_name='users', through='book_clubs.Rating', to='book_clubs.Book'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'book')},
        ),
        migrations.CreateModel(
            name='MeetingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_clubs.book')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_clubs.meeting')),
            ],
            options={
                'unique_together': {('meeting', 'book')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='recommendations',
            field=models.ManyToManyField(related_name='recommended_in', through='book_clubs.MeetingRecommendation', to='book_clubs.Book'),
        ),
    ]
