# Generated by Django 3.2.5 on 2022-03-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0010_auto_20220316_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url_l',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url_m',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url_s',
            field=models.URLField(null=True),
        ),
    ]
