# Generated by Django 3.2.5 on 2022-03-17 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0011_auto_20220317_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url_l',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url_m',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url_s',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='book_chooser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='chosen_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book_clubs.book'),
        ),
    ]
