# Generated by Django 3.2.5 on 2022-03-17 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0012_auto_20220317_0117'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'author', 'year_of_publication', 'publisher')},
        ),
    ]
