# Generated by Django 3.2.5 on 2022-03-26 22:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0013_alter_book_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000000)),
                ('post_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('name_of_user', models.CharField(max_length=30)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_clubs.meeting')),
            ],
        ),
    ]
