# Generated by Django 3.2.5 on 2022-04-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0017_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
